#
#   EDI: Extended-Debug-Info
#         Config v${project.version}

#Defines how often the values of an option are updated (in ticks; 1 sec = 20 ticks)
#Default = 2
update_cycle_count: 2

#All options which are added will be not usable by players. Just add them by their identifier
#For a list of the standard option-identifier look at the github-page of the plugin
blacklisted_options:

#Defines how often the settings-data will be saved to the storage (in ticks; 1 sec = 20 ticks)
#Default = 18000 (=> 15min)
storage_save_cycle: 18000